### ISSUE TITLE
Can't connect to https for WMS server

### ISSUE THREAD

**Issue by ScottEvil** [ROGUE-JCTD/Arbiter-Android#99]
With the update to demo.geoshape.org having ssl, I can't connect with Arbiter anymore. When you try to set up a server you get the error message: "unable to connect to the server, make sure the url is correct"

**Comment by ScottEvil** [comment]
I just checked with the device browser (thanks to Tyler's suggestion) and the browser doesn't consider the cert as valid: "NET::ERR_CERT_AUTHORITY_INVALID"

Nexus 4, Android 5.0, Chrome browser

**Comment by smesdaghi** [comment]
The problem was with the SSL cert chain issue on the particular server. This commit also SHA: e74a76911eb7802ec70748aba74dff013ec8ffe1 allows you to work around the problem but the proper solutions is to make sure cert chain doesn't have any errors. You can test SSL status of a site by using this online tool: https://www.ssllabs.com/ssltest/ if under "Chain Issues" you see "incomplete" the admin of the server needs to make sure that the SSL certificates are their dependent certs are available and in the correct order.
